### ISSUE TITLE
stepwizard language definition

### ISSUE THREAD

**Issue by raiwa** [raiwa/Modular-Checkout#8]
@MOPS-DanCole ,
It seems these definitions are not used anywhere:
define('MODULE_CONTENT_CHECKOUT_PAYMENT_STEPWIZARD_TABLE_HEADING', 'Add the StepWizard on your Checkout Payment Page.');

Can you please remove them from your modules

Or am I missing something??

We are almost done!!
Thanks a lot :-)

**Comment by MOPS-DanCole** [comment]
I'll have a look as soon as I get that last stepwizard done.   BTW, I noticed in the checkout shipping and payment address files that this is a back button at the bottom....after the stepwizard....should there be a back button module for those?

**Comment by raiwa** [comment]
Oh, yes, I forgot. What do you think, they maybe could stay in the file. They are only used if something gets wrong when submitting a new address, I believe.

**Comment by raiwa** [comment]
Although, if we already modularize, it's not a big job.

**Comment by MOPS-DanCole** [comment]
TABLE CONFIGURATION usage returned to normal.

**Comment by MOPS-DanCole** [comment]
I think that's a wrap.  Well done!
