### ISSUE TITLE
modularising processing...

### ISSUE THREAD

**Issue by BrockleyJohn** [raiwa/Modular-Checkout#9]
I don't think that hooks (or actions) are going to work for what Gary's after.

The problem is that they just run - there's no turning them on and off, so you can't use a different one instead you have to overwrite.
[https://github.com/raiwa/Modular-Checkout/blob/modularise_processing/checkout_shipping.php](https://github.com/raiwa/Modular-Checkout/blob/modularise_processing/checkout_shipping.php)
Didn't have much time left tonight but had a look at checkout shipping and think it splits into four sections as indicated. Chunk 4 is clearly content-related.

The first 3 would work in a content or header tags module too.

If we were to take this stuff out of the page file, I think that 1-3 could go in 3 header tags modules while 4 went in the methods content module.

What are your views?

**Comment by BrockleyJohn** [comment]
actually, now I think more on it, ht modules are no good because they aren't specific to the page, so it's content or nothing.

there is precedent for content modules with no content - checkout success redirect old order for example

**Comment by raiwa** [comment]
For the hooks:
If a contribution needs to use hooks to change processing, it would have also a content module which can hold everything what the hook can not have included:
-	Installation script
-	Database changes
-	COnfiguration settings
-	Functions
-	Class extensions
-	Language definitions
If there is no content module, it can be done in a header tag which just holds all of this or another module which can be in a separate module group which does nothing on the public store side and just is used to hold all of this above mentioned.
I do this in some of my add ons in a module group called “store”.
Fort he modularisation of actions etc:
I had a deeper look and tried some moving of processing code.
Maybe I’m missing things, but what I see is the problem of sort order. The order of actions is now defined in a logic correlative way. If we move parts of the actions into the content modules, the order of execution is defined by the sort order of the content modules. As far as I see, changing then the sort order of modules can break the code.
I do not see a way to control the order of the action execution independant of the sort order of the content modules. Or do I miss something there?
Example 1:
This part in checkout_shipping.php:
```
  if ( isset($_POST['action']) && ($_POST['action'] == 'process') && isset($_POST['formid']) && ($_POST['formid'] == $sessiontoken) ) {
    if (!tep_session_is_registered('comments')) tep_session_register('comments');
    if (tep_not_null($_POST['comments'])) {
      $comments = tep_db_prepare_input($_POST['comments']);
    }
```
Looks like it could be moved into the comments module.
But there are the redirects to checkout_payment.php after this snippet.
So if we move it into the comment module, which is included after the shipping method module, and move the shipping method snippet (which contains the redirects to Checkout_payment.php) into the shipping method module, the order is incorrect and the redirects will be executed before the comments are registered.

What seems to be posible to be moved is this part:
```
// get all available shipping quotes
      $quotes = $shipping_modules->quote();

// if no shipping method has been selected, automatically select the cheapest method.
// if the modules status was changed when none were available, to save on implementing
// a javascript force-selection method, also automatically select the cheapest shipping
// method if more than one module is now enabled
        if ( !tep_session_is_registered('shipping') || ( tep_session_is_registered('shipping') && ($shipping == false) && (tep_count_shipping_modules() > 1) ) ) $shipping = $shipping_modules->cheapest();
            
        if ( defined('SHIPPING_ALLOW_UNDEFINED_ZONES') && (SHIPPING_ALLOW_UNDEFINED_ZONES == 'False') && !    tep_session_is_registered('shipping') && ($shipping == false) ) {
        $messageStack->add_session('checkout_address', ERROR_NO_SHIPPING_AVAILABLE_TO_SHIPPING_ADDRESS);
        tep_redirect(tep_href_link('checkout_shipping_address.php', '', 'SSL'));
      }
```
I'll try to do this today and see if there is more possible to move.

**Comment by BrockleyJohn** [comment]
I just pushed a commit with that in to the branch, and I have an idea for the rest, based on the design of checkout_success.
As you say, it needs sort order as well as enable/disable, so I can't see an option other than content modules.

**Comment by raiwa** [comment]
DO you mean to add a second content call (group) for the processes between application top and template top? THey could have a disabled sort order config. constant.
But this architecture would be new.
Otherwise does the fact that checkout_success.php uses content variable which is defined in the actions area change anything?

**Comment by BrockleyJohn** [comment]
and this is how it's done:
[https://github.com/raiwa/Modular-Checkout/commit/1a5fa739db300d66986c7bbdaffc2b41812acb31](https://github.com/raiwa/Modular-Checkout/commit/1a5fa739db300d66986c7bbdaffc2b41812acb31)

It just remains to decide how many modules... my gut says 3

**Comment by BrockleyJohn** [comment]
This is how checkout_success works already

**Comment by raiwa** [comment]
Great, thanks
